### PR TITLE
ML - applied hw1 changes

### LINKED ISSUE #15: add HW1 changes
follow github flow to merge changes (after code review)

### PR DESCRIPTION
**Pull request by michellejli77**
Resolves #15. Increase contrast between button, text, and background color - appearance

### CODE REVIEW

**Comment by michellejli77** [comment]
Resolves #16

**Review by AlexanderChiuy — APPROVED** [review]
LGTM

**Review by joycewu37 — APPROVED** [review]
lgtm!

**Review by mw5-cmu — APPROVED** [review]
lgtm

**Review by roshanr11 — APPROVED** [review]
lgtm!

**Review by huiningliang — APPROVED** [review]

**Pull request merged**
