### PR TITLE
Form basic UI

### LINKED ISSUE #4: Creating basic structure and UI elements of the form
(input boxes, buttons, labels)
 *Separate into different sections (skills, experience, GPA, comments, questions, scoring)

8 hours

Depends on wireframes being completed prior to this task. Order: after wireframes are complete, so that the basic form structure can be made according to the wireframe specifications. Time: familiarizing with codebase and frontend development, as well as buffer time for collaboration

### LINKED ISSUE #6: Form checking/requirements (validation)
(require numbers in phone number field, short answer for email, etc.)

6 hours

This factor depends on the type of questions involved in the form. It is needed because it eliminates errors and extraneous submissions in the process of collecting data. This task is placed here because most of the information included in the questions should also be in the resume, but it creates a quicker way for aggregate data to be calculated without possible invalid values. The 6 hours will be used to adjust requirements to each individual question, as well as limiting the number of characters involved for more specific questions, such as the number of digits needed when inputting GPA.

### PR DESCRIPTION
**Pull request by joycewu37**
Adds resume form Django app. The backend code in this PR is plugged into the generic form template HTML file. Screenshot of form attached. Resolves #4 and resolves #6 
Screen Shot 2021-09-23 at 3 03 10 PM

### CODE REVIEW

**Review by AlexanderChiuy — APPROVED** [review]
LGTM

**Review by michellejli77 — APPROVED** [review]
lgtm!

**Review by huiningliang — APPROVED** [review]

**Review by roshanr11 — APPROVED** [review]
lgtm

**Comment by joycewu37** [comment]
closing due to subsequent form improvements on this branch.

**Pull request merged**
